Initial profiling implementation.
A partially-implemented profiler for client time, which basically just
inserts (optional) gettimeofday calls in various places and stashes data
in a flat file containing one data block per pid.

Signed-off-by: Peter Seebach <peter.seebach@windriver.com>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -28,6 +28,7 @@ opt_rpath=
 opt_memory=
 opt_async=
 opt_xattr=
+opt_profile=false
 opt_passwd_fallback='""'
 
 compile_x86_32=-m32
@@ -41,6 +42,7 @@ usage()
     echo >&2 "           [--suffix=...]"
     echo >&2 "           [--enable-memory-db]"
     echo >&2 "           [--enable-xattr]"
+    echo >&2 "           [--enable-profiling]"
     echo >&2 "           [--enable-force-async]"
     echo >&2 "           [--with-sqlite=...]"
     echo >&2 "           [--with-sqlite-lib=...]"
@@ -104,6 +106,12 @@ do
         ;;
     --enable-force-async=yes | --enable-force-async)
         opt_async=true
+	;;
+    --enable-profiling=no)
+        opt_profiling=false
+        ;;
+    --enable-profiling=yes | --enable-profiling)
+        opt_profiling=true
 	;;
     --enable-xattr=no)
         opt_xattr=false
@@ -243,13 +251,26 @@ else
     FORCE_ASYNC=""
 fi
 
+if getfattr --help >/dev/null 2>&1; then
+    xattr_runs=true
+else
+    xattr_runs=false
+fi
+
+
 if [ -z "$opt_xattr" ]; then
-    if getfattr --help >/dev/null 2>&1; then
+    if $xattr_runs; then
         opt_xattr=true
-	echo "getfattr runs, enabling extended attribute support"
+        echo "getfattr runs, enabling extended attribute support"
     else
         opt_xattr=false
-	echo "getfattr fails, disabling extended attribute support"
+        echo "getfattr fails, disabling extended attribute support"
+    fi
+fi
+
+if $opt_xattr; then
+    if ! $xattr_runs; then
+        echo >&2 "WARNING: getfattr doesn't work, but xattr-related features requestd."
     fi
 fi
 
@@ -287,6 +308,7 @@ touch func_deps.mk
 sed -e '
   s,@PREFIX@,'"$opt_prefix"',g
   s,@XATTR@,'"$opt_xattr"',g
+  s,@PROFILING@,'"$opt_profiling"',g
   s,@LIBDIR@,'"$opt_libdir"',g
   s,@LIB@,'"$opt_lib"',g
   s,@SUFFIX@,'"$opt_suffix"',g
