Add statvfs wrapper
Patch was submitted by <dan.dedrick@gmail.com>, revised to make it
a subport in case someone cares about a Linux system which doesn't
have this function. (Which is probably unlikely, but I am a cautious
sort.)

Signed-off-by: Seebs <seebs@seebs.net>

diff --git a/ports/linux/subports b/ports/linux/subports
--- a/ports/linux/subports
+++ b/ports/linux/subports
@@ -41,3 +41,16 @@ else
 	echo "linux/noxattr"
 fi
 rm -f dummy.c dummy.o
+
+cat > dummy.c <<EOF
+#include <sys/statvfs.h>
+int i;
+EOF
+if ! ${CC} -c -o dummy.o dummy.c >/dev/null 2>&1; then
+	echo >&2 "Warning: Can't compile trivial program using <sys/statvfs.h>".
+	echo >&2 "         xattr support will require that header."
+else
+	echo "linux/statvfs"
+fi
+rm -f dummy.c dummy.o
+
