xattr: adjust for attr 2.4.48 release
Latest versions of attr have removed the xattr.h header,
with the rationale that libc is providing the same wrappers.

attr/attributes.h is providing the ENOATTR definition.

Upstream-Status: Pending
Signed-off-by: Alexander Kanavin <alex.kanavin@gmail.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>

diff --git a/ports/linux/subports b/ports/linux/subports
--- a/ports/linux/subports
+++ b/ports/linux/subports
@@ -29,11 +29,12 @@ fi
 if	$port_xattr; then
 	cat > dummy.c <<EOF
 #include <sys/types.h>
-#include <attr/xattr.h>
+#include <sys/xattr.h>
+#include <attr/attributes.h>
 int i;
 EOF
 	if ! ${CC} -c -o dummy.o dummy.c >/dev/null 2>&1; then
-		echo >&2 "Warning: Can't compile trivial program using <attr/xattr.h>".
+		echo >&2 "Warning: Can't compile trivial program using <attr/attributes.h>".
 		echo >&2 "         xattr support will require that header."
 	fi
 	echo "linux/xattr"
